import React from "react";

interface ReportFooterProps {
  systemName?: string;
  generatedTimestamp: string;
  pageNumber: number;
  totalPages: number;
  isConfidential?: boolean;
}

export default function ReportFooter({
  systemName = "POS System",
  generatedTimestamp,
  pageNumber,
  totalPages,
  isConfidential = false,
}: ReportFooterProps) {
  return (
    <div className="w-full mt-auto pt-4 border-t border-slate-200 flex justify-between items-end text-slate-500 text-[10px] break-inside-avoid">
      {/* Left: System Name & Optional Confidentiality */}
      <div className="flex flex-col items-start">
        <span className="font-medium tracking-wide">
          Generated by {systemName}
        </span>
        {isConfidential && (
          <span className="mt-1 font-bold text-slate-400 uppercase tracking-widest text-[8px]">
            Internal / Confidential Use Only
          </span>
        )}
      </div>

      {/* Center: Timestamp */}
      <div className="text-center text-slate-400 font-mono text-[9px]">
        Generated on: {generatedTimestamp}
      </div>

      {/* Right: Page Numbers */}
      <div className="text-right flex flex-col items-end">
        <span className="font-bold text-slate-600">
          Page {pageNumber} of {totalPages}
        </span>
      </div>
    </div>
  );
}
