export const INVENTORY_MOCK_DATA = [
  {
    id: 1,
    name: 'Holcim Cement 50kg',
    skuInfo: 'HCM-50-001',
    sku: 'HCM-50-001',
    category: 'Cement',
    warehouse: 'Main Store',
    qty: 125,
    minLevel: 50,
    maxLevel: 500,
    unitCost: 'Rs. 1,650',
    totalValue: 'Rs. 206,250',
    status: 'In Stock',
    lastMovement: '18/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 2,
    name: 'Steel Bars 12mm',
    skuInfo: 'STL-BAR-12-001',
    sku: 'STL-BAR-12-001',
    category: 'Steel & Metal',
    warehouse: 'Central Warehouse',
    qty: 0,
    minLevel: 100,
    maxLevel: 800,
    unitCost: 'Rs. 4,500',
    totalValue: 'Rs. 0',
    status: 'Out of Stock',
    lastMovement: '15/01/2026',
    reorder: 'critical',
    image: '/placeholder.png'
  },
  {
    id: 3,
    name: 'Paint (Industrial)',
    skuInfo: 'PNT-IND-001',
    sku: 'PNT-IND-001',
    category: 'Paint & Varnish',
    warehouse: 'Branch 1',
    qty: 35,
    minLevel: 30,
    maxLevel: 150,
    unitCost: 'Rs. 2,850',
    totalValue: 'Rs. 99,750',
    status: 'Low Stock',
    lastMovement: '17/01/2026',
    reorder: 'warning',
    image: '/placeholder.png'
  },
  {
    id: 4,
    name: 'Electrical Cables',
    skuInfo: 'ELC-CBL-001',
    sku: 'ELC-CBL-001',
    category: 'Electrical',
    warehouse: 'Main Store',
    qty: 450,
    minLevel: 100,
    maxLevel: 600,
    unitCost: 'Rs. 1,250',
    totalValue: 'Rs. 562,500',
    status: 'In Stock',
    lastMovement: '18/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 5,
    name: 'Plywood Sheets',
    skuInfo: 'PLY-SHT-001',
    sku: 'PLY-SHT-001',
    category: 'Wood & Timber',
    warehouse: 'Branch 2',
    qty: 280,
    minLevel: 80,
    maxLevel: 400,
    unitCost: 'Rs. 3,200',
    totalValue: 'Rs. 896,000',
    status: 'In Stock',
    lastMovement: '16/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 6,
    name: 'PVC Pipes 4-inch',
    skuInfo: 'PVC-4IN-001',
    sku: 'PVC-4IN-001',
    category: 'Plumbing',
    warehouse: 'Main Store',
    qty: 85,
    minLevel: 40,
    maxLevel: 300,
    unitCost: 'Rs. 850',
    totalValue: 'Rs. 72,250',
    status: 'In Stock',
    lastMovement: '10/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 7,
    name: 'Roofing Sheets (Zn)',
    skuInfo: 'RF-ZN-001',
    sku: 'RF-ZN-001',
    category: 'Roofing',
    warehouse: 'Central Warehouse',
    qty: 12,
    minLevel: 30,
    maxLevel: 200,
    unitCost: 'Rs. 5,500',
    totalValue: 'Rs. 66,000',
    status: 'Low Stock',
    lastMovement: '05/01/2026',
    reorder: 'warning',
    image: '/placeholder.png'
  },
  {
    id: 8,
    name: 'Door Handles (Brass)',
    skuInfo: 'DR-HNDL-001',
    sku: 'DR-HNDL-001',
    category: 'Hardware',
    warehouse: 'Branch 1',
    qty: 150,
    minLevel: 50,
    maxLevel: 500,
    unitCost: 'Rs. 1,200',
    totalValue: 'Rs. 180,000',
    status: 'In Stock',
    lastMovement: '20/12/2025',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 9,
    name: 'Safety Helmets (Yellow)',
    skuInfo: 'SAF-HLM-001',
    sku: 'SAF-HLM-001',
    category: 'Safety',
    warehouse: 'Main Store',
    qty: 45,
    minLevel: 10,
    maxLevel: 100,
    unitCost: 'Rs. 1,800',
    totalValue: 'Rs. 81,000',
    status: 'In Stock',
    lastMovement: '15/12/2025',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 10,
    name: 'Wall Tiles 12x12',
    skuInfo: 'TL-1212-001',
    sku: 'TL-1212-001',
    category: 'Tiles',
    warehouse: 'Branch 2',
    qty: 600,
    minLevel: 200,
    maxLevel: 2000,
    unitCost: 'Rs. 150',
    totalValue: 'Rs. 90,000',
    status: 'In Stock',
    lastMovement: '10/12/2025',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 11,
    name: 'Grout (White)',
    skuInfo: 'GRT-WH-001',
    sku: 'GRT-WH-001',
    category: 'Tiles',
    warehouse: 'Main Store',
    qty: 5,
    minLevel: 20,
    maxLevel: 100,
    unitCost: 'Rs. 450',
    totalValue: 'Rs. 2,250',
    status: 'Low Stock',
    lastMovement: '01/01/2026',
    reorder: 'warning',
    image: '/placeholder.png'
  },
  {
    id: 12,
    name: 'Angle Grinder 4-inch',
    skuInfo: 'TL-P-AG4',
    sku: 'TL-P-AG4',
    category: 'Power Tools',
    warehouse: 'Central Warehouse',
    qty: 0,
    minLevel: 5,
    maxLevel: 25,
    unitCost: 'Rs. 12,500',
    totalValue: 'Rs. 0',
    status: 'Out of Stock',
    lastMovement: '28/12/2025',
    reorder: 'critical',
    image: '/placeholder.png'
  },
  {
    id: 13,
    name: 'Brass Screws 1-inch',
    skuInfo: 'SCR-BR-1',
    sku: 'SCR-BR-1',
    category: 'Fasteners',
    warehouse: 'Branch 1',
    qty: 2500,
    minLevel: 500,
    maxLevel: 10000,
    unitCost: 'Rs. 2',
    totalValue: 'Rs. 5,000',
    status: 'In Stock',
    lastMovement: '12/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 14,
    name: 'White Cement 5k',
    skuInfo: 'HCM-W-005',
    sku: 'HCM-W-005',
    category: 'Cement',
    warehouse: 'Main Store',
    qty: 320,
    minLevel: 50,
    maxLevel: 500,
    unitCost: 'Rs. 450',
    totalValue: 'Rs. 144,000',
    status: 'In Stock',
    lastMovement: '08/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 15,
    name: 'Detergent Industrial 5L',
    skuInfo: 'CHM-DET-5',
    sku: 'CHM-DET-5',
    category: 'Chemicals',
    warehouse: 'Branch 2',
    qty: 18,
    minLevel: 10,
    maxLevel: 50,
    unitCost: 'Rs. 2,400',
    totalValue: 'Rs. 43,200',
    status: 'In Stock',
    lastMovement: '14/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 16,
    name: 'Glass Sheet 4x4',
    skuInfo: 'GLS-44-001',
    sku: 'GLS-44-001',
    category: 'Glass',
    warehouse: 'Central Warehouse',
    qty: 24,
    minLevel: 20,
    maxLevel: 100,
    unitCost: 'Rs. 12,000',
    totalValue: 'Rs. 288,000',
    status: 'In Stock',
    lastMovement: '02/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 17,
    name: 'Aluminium Bar 20ft',
    skuInfo: 'ALM-BR-20',
    sku: 'ALM-BR-20',
    category: 'Steel & Metal',
    warehouse: 'Main Store',
    qty: 90,
    minLevel: 25,
    maxLevel: 150,
    unitCost: 'Rs. 18,500',
    totalValue: 'Rs. 1,665,000',
    status: 'In Stock',
    lastMovement: '11/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 18,
    name: 'Industrial Broom',
    skuInfo: 'TL-BRM-001',
    sku: 'TL-BRM-001',
    category: 'Tools',
    warehouse: 'Branch 1',
    qty: 65,
    minLevel: 20,
    maxLevel: 200,
    unitCost: 'Rs. 950',
    totalValue: 'Rs. 61,750',
    status: 'In Stock',
    lastMovement: '19/12/2025',
    reorder: 'good',
    image: '/placeholder.png'
  },
  {
    id: 19,
    name: 'Wood Chisel Set',
    skuInfo: 'TL-CH-SET',
    sku: 'TL-CH-SET',
    category: 'Tools',
    warehouse: 'Branch 2',
    qty: 8,
    minLevel: 10,
    maxLevel: 50,
    unitCost: 'Rs. 4,500',
    totalValue: 'Rs. 36,000',
    status: 'Low Stock',
    lastMovement: '05/01/2026',
    reorder: 'warning',
    image: '/placeholder.png'
  },
  {
    id: 20,
    name: 'Hacksaw Blades (Pack 10)',
    skuInfo: 'TL-HSB-10',
    sku: 'TL-HSB-10',
    category: 'Tools',
    warehouse: 'Main Store',
    qty: 140,
    minLevel: 40,
    maxLevel: 400,
    unitCost: 'Rs. 350',
    totalValue: 'Rs. 49,000',
    status: 'In Stock',
    lastMovement: '15/01/2026',
    reorder: 'good',
    image: '/placeholder.png'
  }
];
