"use client";

import React, { useEffect, useState, useCallback } from "react";
import {
  X,
  Download,
  RefreshCcw,
  CheckCircle2,
  AlertTriangle,
  Loader2,
  FileCode2,
  Package,
  Filter,
  Printer,
  FolderArchive,
  FileSpreadsheet,
  Sparkles,
  Tag,
} from "lucide-react";
import api from "@/api/axiosInstance";
import { generateCode39SVG } from "@/utils/barcodePrintUtility";

// Load JSZip dynamically for client-side ZIP creation
function loadJSZip(): Promise<any> {
  return new Promise((resolve, reject) => {
    if ((window as any).JSZip) return resolve((window as any).JSZip);
    const script = document.createElement("script");
    script.src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js";
    script.onload = () => resolve((window as any).JSZip);
    script.onerror = () => reject(new Error("Failed to load JSZip"));
    document.head.appendChild(script);
  });
}

/* ─────────────────────────────────────────────────────────────────────────────
   TYPES
───────────────────────────────────────────────────────────────────────────── */
interface LiveProduct {
  id: string;
  name: string;
  sku?: string;
  barcode?: string;
  skuCode?: string;
  sellingPrice?: number | string;
  unitPrice?: number | string;
  price?: number | string;
  category?: { name?: string } | string;
  categoryName?: string;
  subCategory?: { name?: string } | string;
  subCategoryName?: string;
  subcategory?: string;
  subcategoryName?: string;
}

interface NormalizedProduct {
  id: string;
  name: string;
  sku: string;
  category: string;
  subcategory: string;
  stockQty?: number;
}

interface ZPLGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
}

/* ─────────────────────────────────────────────────────────────────────────────
   CODE 39 BARCODE ENCODER — ZPL native ^BC command is used instead
   We just validate the SKU contains only CODE39 chars
───────────────────────────────────────────────────────────────────────────── */
const VALID_CODE39 = /^[A-Z0-9\-. $/+%*]+$/;

function sanitizeSKU(sku: string): string {
  return sku.toUpperCase().replace(/[^A-Z0-9\-. $/+%]/g, "");
}

function truncate(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text;
  return text.substring(0, maxLen - 1) + ".";
}

/* ─────────────────────────────────────────────────────────────────────────────
   ZPL GENERATOR
   Label: 50mm × 25mm = 591 dots × 295 dots @ 203dpi
   Two labels side by side on 100mm wide roll
   6 labels per product = 3 rows × 2 cols (left label and right label)
───────────────────────────────────────────────────────────────────────────── */
function generateZPL(products: NormalizedProduct[]): string {
  // 50mm × 25mm at 203 dpi: 1mm = 8 dots
  // Label width = 50mm = 400 dots, Label height = 25mm = 200 dots
  // Two per row on 100mm roll = 800 dot wide media

  const LABEL_W = 400; // dots (50mm)
  const LABEL_H = 200; // dots (25mm)
  const LABELS_PER_PRODUCT = 6;
  const COLS = 2; // 2 labels per row

  const lines: string[] = [];

  // ZPL header comment
  lines.push(`; ZPL File generated by Trinco Hardware POS`);
  lines.push(`; Label Size: 50mm x 25mm (2-Up roll: 100mm x 25mm)`);
  lines.push(`; Printer: Zebra ZD230 @ 203dpi`);
  lines.push(`; Products: ${products.length} PVC items × 6 labels each`);
  lines.push(`; Total labels: ${products.length * LABELS_PER_PRODUCT}`);
  lines.push(``);

  products.forEach((product) => {
    const sku = sanitizeSKU(product.sku || product.id.slice(0, 12));
    const nameLine1 = truncate(product.name, 28);
    // If name > 28 chars, put rest on line 2
    const nameLine2 =
      product.name.length > 28 ? truncate(product.name.slice(27), 22) : "";

    for (let labelIdx = 0; labelIdx < LABELS_PER_PRODUCT; labelIdx++) {
      const col = labelIdx % COLS; // 0 = left, 1 = right
      const isNewRow = col === 0;

      if (isNewRow) {
        // Start a new label format for left position
        // Left label (X origin = 0)
        lines.push(`^XA`);
        lines.push(`^PW800`); // Print width = 800 dots (100mm)
        lines.push(`^LL200`); // Label length = 200 dots (25mm)
        lines.push(`^LH0,0`); // Label home
        lines.push(`^PR2`);   // Print Speed = 2 in/sec (Slow for ultra-sharp high quality print)
        lines.push(`^MD15`);  // Media Darkness = +15 (High contrast black print)

        // ── LEFT LABEL (col 0) ───────────────────────────────────────────
        // Product name line 1 — top center of left label
        lines.push(`^FO10,8^A0N,20,18^FD${nameLine1}^FS`);
        if (nameLine2) {
          lines.push(`^FO10,30^A0N,16,14^FD${nameLine2}^FS`);
        }

        // Barcode — Code 128 (Subset B), centered on left label (^BY2,2.5 = perfect density for scanner beam)
        const bcY = nameLine2 ? 48 : 38;
        lines.push(`^FO15,${bcY}^BY2,2.5,70^BCN,70,Y,N,N^FD>;${sku}^FS`);

        // SKU text below barcode
        lines.push(`^FO15,174^A0N,18,16^FD${sku}^FS`);

        // Vertical divider line between two labels
        lines.push(`^FO398,0^GB2,200,2^FS`);

        // ── RIGHT LABEL (col 1) — same product ───────────────────────────
        const RX = 402; // Right label X origin (402 dots = ~50mm)

        lines.push(`^FO${RX + 15},8^A0N,20,18^FD${nameLine1}^FS`);
        if (nameLine2) {
          lines.push(`^FO${RX + 15},30^A0N,16,14^FD${nameLine2}^FS`);
        }
        lines.push(
          `^FO${RX + 15},${bcY}^BY2,2.5,70^BCN,70,Y,N,N^FD>;${sku}^FS`
        );
        lines.push(`^FO${RX + 15},174^A0N,18,16^FD${sku}^FS`);

        lines.push(`^PQ1`); // Print 1 copy of this row
        lines.push(`^XZ`);
        lines.push(``);
      }
      // col === 1 means we already added both labels in the col === 0 block above
    }
  });

  return lines.join("\n");
}

/* ─────────────────────────────────────────────────────────────────────────────
   HELPERS
───────────────────────────────────────────────────────────────────────────── */
function normalizeProduct(p: LiveProduct): NormalizedProduct {
  const catRaw = p.category;
  const category =
    typeof catRaw === "object" && catRaw !== null
      ? catRaw.name || ""
      : catRaw || p.categoryName || "";

  const subRaw = p.subCategory;
  const subcategory =
    typeof subRaw === "object" && subRaw !== null
      ? subRaw.name || ""
      : subRaw ||
        p.subCategoryName ||
        p.subcategory ||
        p.subcategoryName ||
        "";

  // Extract stock quantity from API product object (supports Prisma stock relation, quantity, availableQuantity, etc.)
  let rawStock = 0;
  if (Array.isArray((p as any).stocks) && (p as any).stocks.length > 0) {
    rawStock = (p as any).stocks.reduce((acc: number, s: any) => acc + (Number(s.quantity || s.availableQuantity) || 0), 0);
  } else {
    rawStock = (p as any).stockQty ?? (p as any).stock ?? (p as any).quantity ?? (p as any).availableQuantity ?? (p as any).totalStock ?? 0;
  }
  const stockQty = Math.max(0, typeof rawStock === "number" ? rawStock : parseInt(String(rawStock), 10) || 0);

  // Standardize Bajaj Ceiling Fan names (remove 56" so 56" and normal fans of same color consolidate)
  let name = p.name || "Unknown Product";
  if (name.toLowerCase().includes("bajaj") && name.toLowerCase().includes("ceiling fan")) {
    name = name.replace(/56["”'\s]*/gi, "").replace(/\s+/g, " ").trim();
  }

  return {
    id: p.id,
    name,
    sku: p.sku || p.skuCode || p.barcode || p.id.slice(0, 12),
    category,
    subcategory,
    stockQty,
  };
}

function isPVCItem(p: NormalizedProduct): boolean {
  const combined =
    `${p.name} ${p.category} ${p.subcategory}`.toLowerCase();
  return (
    combined.includes("pvc") ||
    combined.includes("fitting") ||
    combined.includes("fittings") ||
    combined.includes("pipe") ||
    combined.includes("elbow") ||
    combined.includes("tee") ||
    combined.includes("reducer") ||
    combined.includes("coupling") ||
    combined.includes("socket") ||
    combined.includes("cap end") ||
    combined.includes("union") ||
    combined.includes("plumbing")
  );
}

/* ─────────────────────────────────────────────────────────────────────────────
   COMPONENT
───────────────────────────────────────────────────────────────────────────── */
export default function ZPLGeneratorModal({
  isOpen,
  onClose,
}: ZPLGeneratorModalProps) {
  const [zipProgress, setZipProgress] = useState<string | null>(null);
  const [allProducts, setAllProducts] = useState<NormalizedProduct[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filterMode, setFilterMode] = useState<"batch7" | "batch6" | "new_batch" | "pvc" | "all">("batch7");
  const [searchText, setSearchText] = useState("");
  const [generated, setGenerated] = useState(false);
  const [totalPages, setTotalPages] = useState(1);
  const [fetchedPages, setFetchedPages] = useState(0);

  const fetchAllProducts = useCallback(async () => {
    setLoading(true);
    setError(null);
    setGenerated(false);
    setFetchedPages(0);

    try {
      // Try fetching all products (pagination aware)
      const collected: NormalizedProduct[] = [];

      // First page — detect if paginated
      const res1 = await api.get("/products", {
        params: { page: 1, limit: 500 },
      });

      const data1 = res1.data;

      // Handle various response shapes
      const extractItems = (data: any): LiveProduct[] => {
        if (Array.isArray(data)) return data;
        if (Array.isArray(data?.data)) return data.data;
        if (Array.isArray(data?.products)) return data.products;
        if (Array.isArray(data?.items)) return data.items;
        if (Array.isArray(data?.results)) return data.results;
        return [];
      };

      // Fetch live stock records from /stock endpoint (matching inventory page)
      const stockMap = new Map<string, number>();
      try {
        const stocksRes = await api.get("/stock").catch(() => api.get("/stocks", { params: { limit: 1000 } }));
        const stocksData = stocksRes.data;
        const stocksList = Array.isArray(stocksData)
          ? stocksData
          : Array.isArray(stocksData?.data)
          ? stocksData.data
          : Array.isArray(stocksData?.items)
          ? stocksData.items
          : [];
        stocksList.forEach((st: any) => {
          const prodId = st.productId || st.product_id || st.product?.id || st.id;
          const q = Number(st.available_quantity ?? st.quantity ?? st.availableQuantity ?? st.qty) || 0;
          if (prodId) {
            stockMap.set(prodId, (stockMap.get(prodId) || 0) + q);
          }
        });
      } catch (e) {
        console.warn("Could not fetch /stock endpoint", e);
      }

      const productMap = new Map<string, NormalizedProduct>();

      const items1 = extractItems(data1);
      items1.forEach((p) => {
        const norm = normalizeProduct(p);
        if (stockMap.has(p.id)) {
          norm.stockQty = stockMap.get(p.id)!;
        }
        productMap.set(norm.id || norm.sku, norm);
      });

      // Check for pagination metadata
      const meta = data1?.meta || data1?.pagination || data1?.page || {};
      const totalPgs =
        meta?.totalPages ||
        meta?.lastPage ||
        meta?.pages ||
        Math.ceil((meta?.total || items1.length) / 500) ||
        1;

      setTotalPages(totalPgs);
      setFetchedPages(1);

      // Fetch remaining pages if any
      if (totalPgs > 1) {
        const pagePromises = [];
        for (let pg = 2; pg <= Math.min(totalPgs, 20); pg++) {
          pagePromises.push(
            api.get("/products", { params: { page: pg, limit: 500 } })
          );
        }
        const results = await Promise.allSettled(pagePromises);
        results.forEach((r) => {
          if (r.status === "fulfilled") {
            extractItems(r.value.data).forEach((p) => {
              const norm = normalizeProduct(p);
              if (stockMap.has(p.id)) {
                norm.stockQty = stockMap.get(p.id)!;
              }
              productMap.set(norm.id || norm.sku, norm);
            });
            setFetchedPages((prev) => prev + 1);
          }
        });
      }

      // Consolidate products with identical standardized names (e.g. Bajaj Ceiling Fan (Black) + Bajaj Ceiling Fan 56" (Black))
      const consolidatedMap = new Map<string, NormalizedProduct>();
      productMap.forEach((prod) => {
        const key = `${prod.name.toLowerCase().trim()}:${prod.category.toLowerCase().trim()}`;
        if (consolidatedMap.has(key)) {
          const existing = consolidatedMap.get(key)!;
          existing.stockQty = (existing.stockQty || 0) + (prod.stockQty || 0);
        } else {
          consolidatedMap.set(key, { ...prod });
        }
      });

      setAllProducts(Array.from(consolidatedMap.values()));
    } catch (err: any) {
      setError(
        err?.response?.data?.message ||
          err?.message ||
          "Failed to fetch products from the server."
      );
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (isOpen) fetchAllProducts();
  }, [isOpen, fetchAllProducts]);

  if (!isOpen) return null;

  // Filter products
  const filtered = allProducts.filter((p) => {
    let matchesMode = true;
    if (filterMode === "batch7") {
      const skuUpper = (p.sku || "").toUpperCase();
      const hkuMatch = skuUpper.match(/HKU_(\d+)/);
      if (hkuMatch) {
        const num = parseInt(hkuMatch[1], 10);
        // Batch 7 items are HKU_60 to HKU_144
        matchesMode = num >= 60 && num <= 144;
      } else {
        const skuNum = parseInt((p.sku || "").replace(/[^0-9]/g, ""), 10);
        matchesMode = skuNum >= 346 && skuNum <= 350;
      }
    } else if (filterMode === "batch6") {
      const skuUpper = (p.sku || "").toUpperCase();
      const hkuMatch = skuUpper.match(/HKU_(\d+)/);
      if (hkuMatch) {
        const num = parseInt(hkuMatch[1], 10);
        // Batch 6 items are HKU_01 to HKU_59
        matchesMode = num >= 1 && num <= 59;
      } else {
        matchesMode = false;
      }
    } else if (filterMode === "pvc") {
      matchesMode = isPVCItem(p);
    } else if (filterMode === "new_batch") {
      const skuStr = (p.sku || "").toUpperCase();
      const isHkuSku = skuStr.includes("HKU_");
      const skuNum = parseInt((p.sku || "").replace(/[^0-9]/g, ""), 10);
      const isNewSku = !isNaN(skuNum) && skuNum >= 355;
      const isAuditItem =
        p.name.toLowerCase().includes("havells") ||
        p.name.toLowerCase().includes("regnis") ||
        p.name.toLowerCase().includes("ingco") ||
        p.name.toLowerCase().includes("makute") ||
        p.name.toLowerCase().includes("singer") ||
        p.name.toLowerCase().includes("broom") ||
        p.name.toLowerCase().includes("mop") ||
        p.name.toLowerCase().includes("wiper") ||
        p.name.toLowerCase().includes("cobweb");
      // Exclude HKU items (which belong to Batch 6 & Batch 7)
      matchesMode = !isHkuSku && (isNewSku || isAuditItem);
    } else if (filterMode === "all") {
      // Exclude Batch 6, Batch 7, and New Batch audit items from "All Products"
      const skuUpper = (p.sku || "").toUpperCase();
      const isHkuSku = skuUpper.includes("HKU_");
      const skuNum = parseInt((p.sku || "").replace(/[^0-9]/g, ""), 10);
      const isNewSku = !isNaN(skuNum) && skuNum >= 346 && skuNum <= 350;
      const isAuditItem =
        p.name.toLowerCase().includes("havells") ||
        p.name.toLowerCase().includes("regnis") ||
        p.name.toLowerCase().includes("ingco") ||
        p.name.toLowerCase().includes("makute") ||
        p.name.toLowerCase().includes("singer") ||
        p.name.toLowerCase().includes("broom") ||
        p.name.toLowerCase().includes("mop") ||
        p.name.toLowerCase().includes("wiper") ||
        p.name.toLowerCase().includes("cobweb");

      matchesMode = !isHkuSku && !isNewSku && !isAuditItem;
    }

    const matchesSearch =
      searchText.trim() === "" ||
      p.name.toLowerCase().includes(searchText.toLowerCase()) ||
      p.sku.toLowerCase().includes(searchText.toLowerCase()) ||
      p.category.toLowerCase().includes(searchText.toLowerCase()) ||
      p.subcategory.toLowerCase().includes(searchText.toLowerCase());
    return matchesMode && matchesSearch;
  });

  const handleDownloadZPL = () => {
    if (filtered.length === 0) return;
    const zpl = generateZPL(filtered);
    const blob = new Blob([zpl], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `PVC_Labels_${filtered.length}products_${Date.now()}.zpl`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setGenerated(true);
  };

  // ── NICELABEL CSV EXPORT ─────────────────────────────────────────────────
  // NiceLabel Designer cannot import code-generated .nlbl files (they are
  // binary templates). Instead, connect a CSV as a "Database" data source in
  // your label template. NiceLabel reads each row and prints Quantity copies.
  const handleDownloadNiceLabelCSV = () => {
    if (filtered.length === 0) return;

    // Header row — map these to your NiceLabel label fields
    const rows: string[] = [
      '"ProductName","SKU","Barcode","Category","Subcategory","Quantity"',
    ];

    filtered.forEach((p) => {
      const sku = sanitizeSKU(p.sku || p.id.slice(0, 12));
      const name = p.name.replace(/"/g, '""'); // escape quotes in CSV
      const cat = (p.category || "").replace(/"/g, '""');
      const sub = (p.subcategory || "").replace(/"/g, '""');
      // Quantity = 6 → NiceLabel will print 6 copies per row
      rows.push(`"${name}","${sku}","${sku}","${cat}","${sub}","6"`);
    });

    const csv = rows.join("\r\n");
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `NiceLabel_DataSource_${filtered.length}products_${Date.now()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setGenerated(true);
  };

  const handleDownloadZip = async () => {
    if (filtered.length === 0) return;
    setZipProgress("Initializing ZIP archive...");

    try {
      const JSZip = await loadJSZip();
      const zip = new JSZip();

      for (let i = 0; i < filtered.length; i++) {
        const item = filtered[i];
        setZipProgress(`Generating PNG ${i + 1} / ${filtered.length}: ${item.name}`);

        const catName = (item.category || "General")
          .replace(/[\\/:*?"<>|]/g, "_")
          .trim();
        const subCatName = item.subcategory
          ? item.subcategory.replace(/[\\/:*?"<>|]/g, "_").trim()
          : "";

        const folderPath = subCatName ? `${catName}/${subCatName}` : catName;
        const folder = zip.folder(folderPath);

        const barcodeValue = item.sku || item.id.slice(0, 12);
        const barcodeSVG = generateCode39SVG(barcodeValue);
        const productName = item.name || "Hardware Product";

        // Render SVG to Canvas -> PNG blob
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");
        canvas.width = 400;
        canvas.height = 200;

        if (ctx) {
          ctx.fillStyle = "#ffffff";
          ctx.fillRect(0, 0, 400, 200);

          // Dynamic font size and line wrapping for Product Name (max 2 lines)
          const nameLen = productName.length;
          const fontSize =
            nameLen > 55 ? 12 :
            nameLen > 45 ? 13 :
            nameLen > 38 ? 14 :
            nameLen > 30 ? 15 :
            nameLen > 24 ? 16 :
            nameLen > 18 ? 18 : 20;

          ctx.fillStyle = "#000000";
          ctx.textAlign = "center";

          // Word wrap helper for canvas
          const wrapText = (text: string, maxWidth: number) => {
            ctx.font = `bold ${fontSize}px Arial`;
            const words = text.split(" ");
            const lines: string[] = [];
            let currentLine = "";

            for (const word of words) {
              const testLine = currentLine ? `${currentLine} ${word}` : word;
              if (ctx.measureText(testLine).width > maxWidth && currentLine) {
                lines.push(currentLine);
                currentLine = word;
              } else {
                currentLine = testLine;
              }
            }
            if (currentLine) lines.push(currentLine);
            return lines.slice(0, 2); // Max 2 lines
          };

          const nameLines = wrapText(productName, 370);
          const lineHeight = fontSize + 3;
          const startY = nameLines.length > 1 ? 20 : 25;

          nameLines.forEach((line, lineIdx) => {
            ctx.font = `bold ${fontSize}px Arial`;
            ctx.fillText(line, 200, startY + lineIdx * lineHeight);
          });

          // SVG Barcode image draw (position dynamically based on name lines)
          const barcodeStartY = nameLines.length > 1 ? 55 : 45;
          const barcodeHeight = nameLines.length > 1 ? 95 : 105;

          const img = new Image();
          const svgBlob = new Blob([barcodeSVG], { type: "image/svg+xml;charset=utf-8" });
          const url = URL.createObjectURL(svgBlob);

          await new Promise((resolve) => {
            img.onload = () => {
              // Draw barcode with 40px left/right Quiet Zone margin for scanner detection
              ctx.drawImage(img, 40, barcodeStartY, 320, barcodeHeight);
              URL.revokeObjectURL(url);
              resolve(true);
            };
            img.onerror = () => {
              URL.revokeObjectURL(url);
              resolve(false);
            };
            img.src = url;
          });

          // SKU text at bottom
          ctx.font = "bold 16px Arial";
          ctx.fillText(barcodeValue, 200, 182);
        }

        const pngDataUrl = canvas.toDataURL("image/png");
        const base64Data = pngDataUrl.replace(/^data:image\/png;base64,/, "");

        // Prefix PNG file name strictly with the product's live inventory stock quantity (e.g., 200_25 mm Elbow 45°_SKU_006.png)
        const qtyPrefix = typeof item.stockQty === "number" ? `${item.stockQty}` : "0";
        const safeFileName = `${qtyPrefix}_${item.name.replace(/[\\/:*?"<>|]/g, "_")}_${barcodeValue}.png`;
        folder.file(safeFileName, base64Data, { base64: true });
      }

      setZipProgress("Compressing ZIP archive...");
      const zipBlob = await zip.generateAsync({ type: "blob" });

      const zipUrl = URL.createObjectURL(zipBlob);
      const a = document.createElement("a");
      a.href = zipUrl;
      const prefix =
        filterMode === "batch7"
          ? "Batch7_HKU_Labels"
          : filterMode === "batch6"
          ? "Batch6_HKU_Labels"
          : filterMode === "pvc"
          ? "PVC_Fittings_Labels"
          : "Catalog_Barcodes";
      a.download = `${prefix}_${filtered.length}items_${Date.now()}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(zipUrl);
    } catch (err: any) {
      alert("Error generating ZIP archive: " + (err.message || err));
    } finally {
      setZipProgress(null);
    }
  };

  const handlePrintAllHTML = () => {
    if (filtered.length === 0) return;

    const labelPairs: string[] = [];

    filtered.forEach((item, itemIdx) => {
      const barcodeValue = item.sku || item.id.slice(0, 12);
      const barcodeSVG = generateCode39SVG(barcodeValue);
      const productName = item.name || "Hardware Product";

      for (let i = 0; i < 6; i += 2) {
        const nameLen = productName.length;
        // Aggressively scale down font for long names so full name is always visible
        const fontSize =
          nameLen > 55 ? '4pt' :
          nameLen > 45 ? '4.5pt' :
          nameLen > 38 ? '5pt' :
          nameLen > 30 ? '5.5pt' :
          nameLen > 24 ? '6pt' :
          nameLen > 18 ? '7pt' : '8pt';

        const makeCard = () => `
          <div class="label-card">
            <div class="prod-name" style="font-size: ${fontSize};">${productName}</div>
            <div class="barcode-wrapper">${barcodeSVG}</div>
            <div class="sku-text">${barcodeValue}</div>
          </div>`;

        labelPairs.push(`
          <div class="label-row">
            ${makeCard()}
            ${makeCard()}
          </div>`);
      }
    });

    const printHTML = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Bulk Print ${filtered.length} Products</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }

  @page {
    size: 100mm 25mm;
    margin: 0;
  }

  html, body {
    width: 100mm;
    height: 25mm;
    margin: 0;
    padding: 0;
    background: white;
    -webkit-print-color-adjust: exact;
  }

  .label-row {
    width: 100mm;
    height: 25mm;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-around;
    page-break-after: always;
    break-after: page;
    box-sizing: border-box;
    margin-left: -3mm !important;
  }

  .label-row:last-child {
    page-break-after: avoid;
    break-after: avoid;
  }

  .label-card {
    width: 48mm;
    height: 23mm;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;
    padding: 1.5mm 1mm;
    background: white;
    text-align: center;
    overflow: hidden;
  }

  .prod-name {
    font-family: Arial, sans-serif;
    font-weight: 900;
    color: #000;
    white-space: normal;
    word-break: break-word;
    overflow-wrap: break-word;
    width: 100%;
    max-height: 7mm;
    overflow: hidden;
    line-height: 1.1;
    letter-spacing: -0.02em;
    text-align: center;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
  }

  .barcode-wrapper {
    width: 95%;
    height: 10mm;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .sku-text {
    font-family: Arial, sans-serif;
    font-size: 7.5pt;
    font-weight: 900;
    color: #000;
    letter-spacing: 0.04em;
    line-height: 1;
  }
</style>
</head>
<body>
${labelPairs.join("")}
<script>
  window.onload = function() {
    setTimeout(function() { window.print(); }, 500);
  };
</script>
</body>
</html>`;

    const win = window.open("", "_blank");
    if (win) {
      win.document.write(printHTML);
      win.document.close();
    } else {
      alert("Pop-up blocked! Please allow pop-ups for this site.");
    }
  };

  // Group by category for display
  const groupedDisplay = filtered.reduce<Record<string, NormalizedProduct[]>>(
    (acc, p) => {
      const key = p.subcategory || p.category || "Other";
      if (!acc[key]) acc[key] = [];
      acc[key].push(p);
      return acc;
    },
    {}
  );

  const totalLabels = filtered.length * 6;
  const totalRows = filtered.length * 3;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-md p-4">
      <div className="bg-white rounded-3xl shadow-2xl w-full max-w-2xl border border-gray-100 overflow-hidden max-h-[90vh] flex flex-col">
        {/* ── HEADER ─────────────────────────────────────────────────────── */}
        <div className="flex items-center justify-between px-6 py-4 bg-gradient-to-r from-slate-900 to-slate-800 text-white shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-teal-500/20 border border-teal-400/30 flex items-center justify-center">
              <FileCode2 className="w-5 h-5 text-teal-300" />
            </div>
            <div>
              <h2 className="text-[15px] font-black tracking-tight">
                ZPL Label Generator
              </h2>
              <p className="text-[11px] text-slate-400 font-medium">
                Zebra ZD230 · 50mm×25mm · 6 labels per product
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-xl flex items-center justify-center hover:bg-slate-700 transition-colors text-slate-400 hover:text-white"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* ── BODY ───────────────────────────────────────────────────────── */}
        <div className="flex flex-col flex-1 overflow-hidden">
          {/* Controls bar */}
          <div className="px-5 py-3 border-b border-gray-100 bg-gray-50/80 shrink-0 space-y-2">
            {/* Filter mode toggles */}
            <div className="flex items-center justify-between flex-wrap gap-2">
              <div className="flex items-center gap-1.5 bg-white border border-gray-200 p-1 rounded-xl overflow-x-auto max-w-full">
                <button
                  onClick={() => setFilterMode("batch7")}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-black transition-all whitespace-nowrap ${
                    filterMode === "batch7"
                      ? "bg-purple-600 text-white shadow-sm"
                      : "text-gray-600 hover:bg-gray-50"
                  }`}
                >
                  <Tag className="w-3 h-3 text-purple-200" />
                  🏷️ Batch 7 (HKU_60–144)
                </button>
                <button
                  onClick={() => setFilterMode("batch6")}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-black transition-all whitespace-nowrap ${
                    filterMode === "batch6"
                      ? "bg-indigo-600 text-white shadow-sm"
                      : "text-gray-600 hover:bg-gray-50"
                  }`}
                >
                  <Tag className="w-3 h-3 text-indigo-200" />
                  🏷️ Batch 6 (HKU_01–59)
                </button>
                <button
                  onClick={() => setFilterMode("new_batch")}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-black transition-all whitespace-nowrap ${
                    filterMode === "new_batch"
                      ? "bg-amber-600 text-white shadow-sm"
                      : "text-gray-600 hover:bg-gray-50"
                  }`}
                >
                  <Sparkles className="w-3 h-3 text-amber-200" />
                  ✨ New Batch (Audit 4/9/26)
                </button>
                <button
                  onClick={() => setFilterMode("pvc")}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-black transition-all whitespace-nowrap ${
                    filterMode === "pvc"
                      ? "bg-teal-600 text-white shadow-sm"
                      : "text-gray-500 hover:bg-gray-50"
                  }`}
                >
                  <Filter className="w-3 h-3" />
                  PVC / Fittings Only
                </button>
                <button
                  onClick={() => setFilterMode("all")}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-black transition-all whitespace-nowrap ${
                    filterMode === "all"
                      ? "bg-slate-700 text-white shadow-sm"
                      : "text-gray-500 hover:bg-gray-50"
                  }`}
                >
                  <Package className="w-3 h-3" />
                  📦 Original Catalog (Base Items)
                </button>
              </div>

              <button
                onClick={fetchAllProducts}
                disabled={loading}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-bold text-slate-600 hover:bg-slate-100 transition-colors border border-slate-200 bg-white disabled:opacity-50"
              >
                <RefreshCcw
                  className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`}
                />
                Refresh
              </button>
            </div>

            {/* Search */}
            <input
              type="text"
              placeholder="Search by name, SKU, category..."
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
              className="w-full px-3 py-2 rounded-xl border border-gray-200 text-[12px] font-medium text-gray-700 placeholder:text-gray-400 bg-white focus:outline-none focus:ring-2 focus:ring-teal-400/40"
            />
          </div>

          {/* Product list */}
          <div className="flex-1 overflow-y-auto">
            {loading && (
              <div className="flex flex-col items-center justify-center py-16 gap-3">
                <Loader2 className="w-8 h-8 text-teal-500 animate-spin" />
                <div className="text-center">
                  <p className="text-[13px] font-black text-gray-700">
                    Fetching inventory...
                  </p>
                  <p className="text-[11px] text-gray-400 font-medium mt-0.5">
                    {fetchedPages > 0 &&
                      `Loaded ${fetchedPages} / ${totalPages} pages`}
                  </p>
                </div>
              </div>
            )}

            {!loading && error && (
              <div className="flex flex-col items-center justify-center py-12 gap-3 px-6">
                <div className="w-12 h-12 rounded-2xl bg-red-50 border border-red-200 flex items-center justify-center">
                  <AlertTriangle className="w-6 h-6 text-red-500" />
                </div>
                <div className="text-center">
                  <p className="text-[13px] font-black text-gray-800">
                    Could not load inventory
                  </p>
                  <p className="text-[11px] text-gray-500 mt-1 font-medium max-w-xs">
                    {error}
                  </p>
                  <p className="text-[11px] text-amber-600 mt-2 font-bold bg-amber-50 px-3 py-1.5 rounded-lg border border-amber-200 inline-block">
                    Make sure the backend is running at localhost:8080
                  </p>
                </div>
                <button
                  onClick={fetchAllProducts}
                  className="px-4 py-2 bg-slate-900 text-white rounded-xl text-[12px] font-black hover:bg-slate-700 transition-colors mt-1"
                >
                  Try Again
                </button>
              </div>
            )}

            {!loading && !error && allProducts.length === 0 && (
              <div className="flex flex-col items-center justify-center py-12 gap-2 text-center px-6">
                <Package className="w-10 h-10 text-gray-300" />
                <p className="text-[13px] font-black text-gray-500">
                  No products found
                </p>
                <p className="text-[11px] text-gray-400 font-medium">
                  The API returned an empty product list
                </p>
              </div>
            )}

            {!loading && !error && allProducts.length > 0 && filtered.length === 0 && (
              <div className="flex flex-col items-center justify-center py-12 gap-2 text-center px-6">
                <Filter className="w-10 h-10 text-gray-300" />
                <p className="text-[13px] font-black text-gray-500">
                  No PVC / Fitting items found
                </p>
                <p className="text-[11px] text-gray-400 font-medium max-w-xs">
                  Try switching to "All Products" or check your category names
                  contain PVC/Fitting/Pipe keywords
                </p>
                <button
                  onClick={() => setFilterMode("all")}
                  className="px-3 py-1.5 bg-slate-900 text-white rounded-lg text-[11px] font-black hover:bg-slate-700 mt-1"
                >
                  Show All Products
                </button>
              </div>
            )}

            {!loading && !error && filtered.length > 0 && (
              <div className="p-4 space-y-3">
                {Object.entries(groupedDisplay).map(([groupName, items]) => (
                  <div key={groupName}>
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className="text-[10px] font-black text-teal-700 bg-teal-50 border border-teal-200 px-2 py-0.5 rounded-full uppercase tracking-wider">
                        {groupName}
                      </span>
                      <span className="text-[10px] text-gray-400 font-medium">
                        {items.length} item{items.length !== 1 ? "s" : ""} ·{" "}
                        {items.length * 6} labels
                      </span>
                    </div>
                    <div className="space-y-1">
                      {items.map((p, idx) => (
                        <div
                          key={p.id}
                          className="flex items-center justify-between px-3 py-2 rounded-xl border border-gray-100 bg-gray-50/60 hover:bg-gray-100/70 transition-colors"
                        >
                          <div className="flex items-center gap-2.5">
                            <div className="w-6 h-6 rounded-lg bg-slate-800 text-white text-[10px] font-black flex items-center justify-center shrink-0">
                              {idx + 1}
                            </div>
                            <div>
                              <p className="text-[12px] font-black text-gray-900 leading-tight">
                                {p.name}
                              </p>
                              <p className="text-[10px] font-mono font-bold text-slate-500">
                                {p.sku}
                              </p>
                            </div>
                          </div>
                          <div className="flex items-center gap-1 shrink-0">
                            {[0, 1, 2, 3, 4, 5].map((i) => (
                              <div
                                key={i}
                                className="w-3 h-4 bg-slate-800 rounded-sm opacity-80"
                                style={{ opacity: 0.4 + i * 0.1 }}
                              />
                            ))}
                            <span className="text-[9px] text-gray-400 font-bold ml-1">
                              ×6
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* ── FOOTER ───────────────────────────────────────────────────── */}
          {!loading && !error && filtered.length > 0 && (
            <div className="px-5 py-3.5 border-t border-gray-100 bg-gray-50 shrink-0">
              {/* Summary stats */}
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div className="text-center">
                    <p className="text-[18px] font-black text-slate-900 leading-none">
                      {filtered.length}
                    </p>
                    <p className="text-[9px] text-gray-500 font-bold uppercase tracking-wide">
                      Products
                    </p>
                  </div>
                  <div className="w-px h-8 bg-gray-200" />
                  <div className="text-center">
                    <p className="text-[18px] font-black text-teal-700 leading-none">
                      {totalLabels}
                    </p>
                    <p className="text-[9px] text-gray-500 font-bold uppercase tracking-wide">
                      Total Labels
                    </p>
                  </div>
                  <div className="w-px h-8 bg-gray-200" />
                  <div className="text-center">
                    <p className="text-[18px] font-black text-slate-900 leading-none">
                      {totalRows}
                    </p>
                    <p className="text-[9px] text-gray-500 font-bold uppercase tracking-wide">
                      Rows Printed
                    </p>
                  </div>
                </div>

                {generated && (
                  <div className="flex items-center gap-1.5 text-emerald-700 bg-emerald-50 px-3 py-1.5 rounded-xl border border-emerald-200">
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span className="text-[11px] font-black">
                      ZPL Downloaded!
                    </span>
                  </div>
                )}
              </div>

              {/* ZPL instructions */}
              <div className="text-[10px] text-amber-800 bg-amber-50 border border-amber-200 px-3 py-2 rounded-xl mb-3 font-medium leading-relaxed">
                <span className="font-black">🖨️ How to print ZPL:</span> Open <span className="font-black">Zebra Setup Utilities</span> → select ZD230 printer → click <span className="font-black">"Open Communication With Printer"</span> → click <span className="font-black">Action → Send File</span> → select .zpl file → click <span className="font-black">Send To Printer</span>.
              </div>

              {/* NiceLabel instructions */}
              <div className="text-[10px] text-blue-800 bg-blue-50 border border-blue-200 px-3 py-2 rounded-xl mb-2 font-medium leading-relaxed">
                <span className="font-black">📋 NiceLabel users:</span> Download the CSV → open NiceLabel Designer → connect CSV as a <span className="font-black">Database source</span> on your label template → map <span className="font-mono font-black">ProductName</span>, <span className="font-mono font-black">Barcode</span>, <span className="font-mono font-black">Quantity</span> fields → Print All. NiceLabel will auto-print 6 labels per product row.
              </div>

              <div className="flex items-center justify-between gap-2">
                <button
                  onClick={onClose}
                  className="px-4 py-2 rounded-xl text-[12px] font-bold text-gray-600 hover:bg-gray-100 transition-colors border border-gray-200"
                >
                  Close
                </button>
                <div className="flex items-center gap-2 flex-wrap justify-end">
                  <button
                    onClick={handleDownloadNiceLabelCSV}
                    className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 text-white rounded-xl text-[12px] font-black transition-all active:scale-95 shadow-md shadow-blue-600/20 border border-blue-500/30"
                  >
                    <FileSpreadsheet className="w-3.5 h-3.5 text-blue-100" />
                    NiceLabel CSV
                  </button>
                  <button
                    onClick={handleDownloadZip}
                    disabled={!!zipProgress}
                    className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-purple-700 to-indigo-700 hover:from-purple-800 hover:to-indigo-800 text-white rounded-xl text-[12px] font-black transition-all active:scale-95 shadow-md shadow-indigo-700/20 disabled:opacity-50 border border-purple-600/30"
                  >
                    {zipProgress ? (
                      <Loader2 className="w-3.5 h-3.5 animate-spin text-purple-200" />
                    ) : (
                      <FolderArchive className="w-3.5 h-3.5 text-purple-200" />
                    )}
                    {zipProgress ? zipProgress : `📦 ZIP PNGs`}
                  </button>
                  <button
                    onClick={handlePrintAllHTML}
                    className="flex items-center gap-2 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-[12px] font-black transition-all active:scale-95 shadow-md shadow-emerald-600/20"
                  >
                    <Printer className="w-3.5 h-3.5" />
                    🖨️ Print All
                  </button>
                  <button
                    onClick={handleDownloadZPL}
                    className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-teal-600 to-emerald-600 hover:from-teal-700 hover:to-emerald-700 text-white rounded-xl text-[13px] font-black shadow-lg shadow-teal-600/25 transition-all active:scale-95"
                  >
                    <Download className="w-4 h-4" />
                    ZPL File
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
